name: Release to Github
on:
  workflow_dispatch:

jobs:
  build:
    name: release-github
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Publish to Github
        run: |
          ./gradlew publish -i "-Pgpr.repo=$${{ vars.GHP_REPO }}"
          mvn deploy -Pgithub "-DaltDeploymentRepository=releaseRepository::default::${{ vars.GHP_REPO }}"
        shell: bash
        env:
          GHP_USERNAME: ${{ secrets.GHP_USERNAME }}
          GHP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
